#Main1.cc: Depends on prog1.cc, prog2.cc
#main2.cc Dpeneds on prog1.cc prog3.cc
#main3.cc does not depend on other files
#prog1.cc depends on prog1.h prog2.h
#prog2.cc depends on prog2.h
#prog3.cc does not depend on any files


echo about to make files 
all : main1 main2 main3 

main1: main1.o pro1.o prog2.o
	g++ -ggdb main1.o prog1.o prog2.o -o main1

main2: main2.o prog1.o prog3.o
	g++ -ggdb main2.o prog1.o prog3.o -o main2

main3: main3.cc
	g++ -ggdb main3.cc -o main3

prog1.o: prog1.cc prog1.h prog2.h
	g++ -ggdb -c prog1.cc

prgo2.o: prog2.cc prog2.h
	g++ -ggdb -c prog2.cc

prog3.o: prog3.cc
	g+ -ggdb -c prog3.cc

clean: 
	rm -rf *~ *.o  
